### ISSUE TITLE
idk what is this

### ISSUE THREAD

**Issue by xgenos** [hugolgst/vimsence#67]
when ever i open my vim it shows something like this and the presence isn't working idk what to do 

```
Error detected while processing function DiscordUpdatePresence[1]..<SNR>37_InitializeDiscord
[4]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/genos/.config/nvim/plugged/vimsence/python/vimsence.py", line 62, in <module>
    has_thumbnail = list(set(has_thumbnail + custom_icons.values()))
TypeError: can only concatenate list (not "dict_values") to list
Press ENTER or type command to continue
Error detected while processing function DiscordUpdatePresence[2]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vimsence' is not defined
```

**Comment by Xhendos** [comment]
I just tried to install this plugin and stumbled upon the same issue. Seems like it is unmaintained now to me.

**Comment by tskxz** [comment]
+1
